- app/controllers/ProcedureTypeController.scala
- app/forms/ProcedureTypeFormProvider.scala
- app/models/ProcedureType.scala
- app/navigation/Navigator.scala
- app/pages/ProcedureTypePage.scala
- app/utils/CheckYourAnswersHelper.scala
- conf/app.routes
- conf/messages.en
- conf/views/declarationType.njk
- conf/views/procedureType.njk
- test/controllers/ProcedureTypeControllerSpec.scala
- test/forms/ProcedureTypeFormProviderSpec.scala
- test/generators/ModelGenerators.scala
- test/generators/UserAnswersEntryGenerators.scala
- test/generators/UserAnswersGenerator.scala
- test/models/ProcedureTypeSpec.scala
- test/navigation/NavigatorSpec.scala
- test/pages/ProcedureTypePageSpec.scala
> Ctctraders 668 - Procedure Type page

- app/forms/DeclarationPlaceFormProvider.scala
- project/AppDependencies.scala
- test/forms/DeclarationPlaceFormProviderSpec.scala
Reverts hmrc/declare-transit-movement-departure-frontend#22
> Revert "CTCTRADRRS- 670 : created declaration place page"

- app/controllers/goodsSummary/ConfirmRemoveSealsController.scala
- app/forms/ConfirmRemoveSealsFormProvider.scala
- app/navigation/GoodsSummaryNavigator.scala
- app/pages/ConfirmRemoveSealsPage.scala
- app/utils/GoodsSummaryCheckYourAnswersHelper.scala
- app/utils/SectionsHelper.scala
- conf/app.routes
- conf/messages.en
- conf/views/confirmRemoveSeals.njk
- test/controllers/goodsSummary/AddSealsLaterControllerSpec.scala
- test/controllers/goodsSummary/ConfirmRemoveSealControllerSpec.scala
- test/controllers/goodsSummary/ConfirmRemoveSealsControllerSpec.scala
- test/forms/ConfirmRemoveSealsFormProviderSpec.scala
- test/generators/PageGenerators.scala
- test/generators/UserAnswersEntryGenerators.scala
- test/generators/UserAnswersGenerator.scala
- test/navigation/GoodsSummaryNavigatorSpec.scala
- test/pages/ConfirmRemoveSealsPageSpec.scala
- test/utils/SectionsHelperSpec.scala
Created new page for confirm remove seals. Update Navigation. Fix bug for status and some refactors on tests
> CTCTRADERS-1066

- app/models/XMLReads.scala
- app/models/messages/DeclarationRequest.scala
- app/models/messages/Meta.scala
- app/repositories/InterchangeControlReferenceIdRepository.scala
- test/generators/Generators.scala
- test/generators/MessagesModelGenerators.scala
- test/models/messages/DeclarationRequestSpec.scala
- test/models/messages/InterchangeControlReferenceSpec.scala
- test/models/messages/MetaSpec.scala
- Add Meta model
- Add initial DeclarationRequest model
> CTCTRADERS-1091: Add Meta model

- app/models/LocalReferenceNumber.scala
- app/models/messages/DeclarationRequest.scala
- app/models/messages/Header.scala
- test/generators/Generators.scala
- test/generators/MessagesModelGenerators.scala
- test/models/messages/DeclarationRequestSpec.scala
- test/models/messages/HeaderSpec.scala
- Added Header model
Note: Given the confussion with IE007 and what the nodes related to I've left the parameter names to reflect the XML node names. If these need changing do it when we do the transformation from user answers to DeclarationRequest
> CTCTRADERS-1092: Add Header model

- app/models/messages/DeclarationRequest.scala
- app/models/messages/Seals.scala
- app/models/messages/guarantee/Guarantee.scala
- app/models/messages/guarantee/GuaranteeReference.scala
- test/generators/Generators.scala
- test/generators/MessagesModelGenerators.scala
- test/models/messages/DeclarationRequestSpec.scala
- test/models/messages/SealsSpec.scala
- test/models/messages/guarantee/GuaranteeReferenceSpec.scala
- test/models/messages/guarantee/GuaranteeSpec.scala
Add Seals
Add Guarantee
Add GuaranteeReference
> CTCTRADERS-1095/1121

- app/config/FrontendAppConfig.scala
- app/controllers/guaranteeDetails/GuaranteeReferenceController.scala
- app/forms/LiabilityAmountFormProvider.scala
- app/forms/OtherReferenceFormProvider.scala
- app/forms/guaranteeDetails/GuaranteeReferenceFormProvider.scala
- app/forms/untitled.sc
- app/models/GuaranteeType.scala
- app/models/messages/guarantee/GuaranteeReference.scala
- app/navigation/GoodsSummaryNavigator.scala
- app/navigation/GuaranteeDetailsNavigator.scala
- app/pages/guaranteeDetails/GuaranteeTypePage.scala
- app/utils/GuaranteeDetailsCheckYourAnswersHelper.scala
- app/utils/SectionsHelper.scala
- conf/messages.en
- conf/views/liabilityAmount.njk
- test/controllers/guaranteeDetails/GuaranteeReferenceControllerSpec.scala
- test/controllers/guaranteeDetails/LiabilityAmountControllerSpec.scala
- test/controllers/guaranteeDetails/OtherReferenceControllerSpec.scala
- test/forms/GuaranteeReferenceFormProviderSpec.scala
- test/forms/LiabilityAmountFormProviderSpec.scala
- test/forms/OtherReferenceFormProviderSpec.scala
- test/navigation/GuaranteeDetailsNavigatorSpec.scala
- test/utils/SectionsHelperSpec.scala
- test/viewModels/GuaranteeDetailsCheckYourAnswersViewModelSpec.scala
Draft PR for Nav. There may be changes as new liability amount page to be implemented with different validation for the alternative route.
> CTCTRADERS-1107

- conf/messages.en
- conf/views/consigneeAddress.njk
- conf/views/consignorAddress.njk
- conf/views/guaranteeDetails/guaranteeType.njk
- Updating validation text
- Adding field level error messages
> CTCTRADERS-1112 | Fixing various validation messages

- app/config/FrontendAppConfig.scala
- app/connectors/DepartureMovementConnector.scala
- app/connectors/ReferenceDataConnector.scala
- conf/application.conf
- project/AppDependencies.scala
- test/connectors/DepartureMovementConnectorSpec.scala
Adding in basic connector and tests
> adding in connector

- app/controllers/addItems/TotalNetMassController.scala
- app/forms/TotalNetMassFormProvider.scala
- app/models/domain/NetMass.scala
- app/pages/AddTotalNetMassPage.scala
- app/pages/ItemDescriptionPage.scala
- app/pages/ItemTotalGrossMassPage.scala
- app/pages/TotalNetMassPage.scala
- app/utils/AddItemsCheckYourAnswersHelper.scala
- conf/app.routes
- conf/messages.en
- conf/views/totalNetMass.njk
- test/controllers/addItems/TotalNetMassControllerSpec.scala
- test/forms/TotalNetMassFormProviderSpec.scala
- test/generators/PageGenerators.scala
- test/generators/UserAnswersEntryGenerators.scala
- test/generators/UserAnswersGenerator.scala
- test/pages/ItemDescriptionPageSpec.scala
- test/pages/TotalNetMassPageSpec.scala
Also update path for the 4 item details pages created
> CTCTRADERS-1162 -Create TotalNetMass page

- app/connectors/DepartureMovementConnector.scala
- app/controllers/movementDetails/MovementDetailsCheckYourAnswersController.scala
- app/controllers/movementDetails/PreLodgeDeclarationController.scala
- app/forms/movementDetails/PreLodgeDeclarationFormProvider.scala
- app/navigation/MovementDetailsNavigator.scala
- app/pages/ProcedureTypePage.scala
- app/pages/movementDetails/PreLodgeDeclarationPage.scala
- app/utils/MovementDetailsCheckYourAnswersHelper.scala
- conf/app.routes
- conf/messages.en
- conf/views/movementDetails/preLodgeDeclaration.njk
- test/connectors/DepartureMovementConnectorSpec.scala
- test/controllers/movementDetails/MovementDetailsCheckYourAnswersControllerSpec.scala
- test/controllers/movementDetails/PreLodgeDeclarationControllerSpec.scala
- test/forms/movementDetails/PreLodgeDeclarationFormProviderSpec.scala
- test/generators/PageGenerators.scala
- test/generators/UserAnswersEntryGenerators.scala
- test/generators/UserAnswersGenerator.scala
- test/navigation/MovementDetailsNavigatorSpec.scala
- test/pages/ProcedureTypePageSpec.scala
- test/pages/movementDetails/PreLodgeDeclarationPageSpec.scala
Adding in pre-lodge question page, updated Navigation and CYA
> Ctctraders 962

- .gitignore
- app/models/journeyDomain/MovementDetails.scala
- app/models/journeyDomain/ParseUserAnswers.scala
- app/models/journeyDomain/RouteDetails.scala
- app/models/journeyDomain/UserAnswersParser.scala
- app/models/journeyDomain/package.scala
- app/pages/ArrivalTimesAtOfficePage.scala
- test/base/GeneratorSpec.scala
- test/base/SpecBase.scala
- test/generators/Generators.scala
- test/generators/ModelGenerators.scala
- test/models/journeyDomain/MovementDetailsSpec.scala
- test/models/journeyDomain/RouteDetailsSpec.scala
- test/pages/ArrivalTimesAtOfficePageSpec.scala
Add models for journey sections and a parser for UserAnswers that can construct these models using existing Gettable
> CTCTRADERS-1098 Parse journey models from UserAnswers

- app/config/FrontendAppConfig.scala
- app/config/Module.scala
- app/controllers/actions/DataRequiredAction.scala
- app/controllers/actions/DataRetrievalAction.scala
- app/controllers/actions/IdentifierAction.scala
- app/repositories/InterchangeControlReferenceCollection.scala
- app/repositories/InterchangeControlReferenceIdRepository.scala
- app/repositories/RepositoryModule.scala
- app/repositories/SessionCollection.scala
- app/repositories/SessionCollectionIndexManager.scala
- app/repositories/SessionRepository.scala
- app/repositories/SimpleMongoIndexConfig.scala
- conf/application.conf
- test/base/MockNunjucksRendererApp.scala
- test/renderer/RendererSpec.scala
- test/repositories/TestRepositoryModule.scala
- test/resources/test.application.conf
- Optimize Module binding for application
- Use mock app with fake renderer in RendererSpec
- Refactor repository package, remove eager bindings in tests
> CTCTRADERS 1231

- app/models/messages/DeclarationRequest.scala
- app/models/messages/goodsitem/GoodsItem.scala
- app/models/messages/header/Header.scala
- app/models/messages/header/Transport.scala
- test/generators/MessagesModelGenerators.scala
- test/models/messages/goodsitem/GoodsItemSpec.scala
- test/models/messages/header/HeaderSpec.scala
- test/models/messages/header/TransportSpec.scala
Some optional xml nodes were missing off the Header and GoodsItem, this is a PR to add these optional items in.
> CTCTRADERS-1089: Add missing attributes to Header and GoodsItem

- test/base/MockNunjucksRendererApp.scala
- test/controllers/AddSecurityDetailsControllerSpec.scala
- Add better integration with GuiceOneAppPerSuite
- Use single app for AddSecurityDetailsControllerSpec.
> CTCTRADERS-1231 Integrate controller tests with mock renderer, data retreival and session repository

- test/base/MockNunjucksRendererApp.scala
Remove deprecated warning to stabilise build
> Remove deprecated warning

- app/derivable/DeriveNumberOfDocuments.scala
- app/utils/AddItemsCheckYourAnswersHelper.scala
- app/viewModels/AddItemsCheckYourAnswersViewModel.scala
- conf/messages.en
- test/viewModels/AddItemsCheckYourAnswersViewModelSpec.scala
In the interest of a smaller commit, there are some outstanding issues:
TODO
- Update A to go to add document when implemented
- Add rows that require documentIndex argument
> CTCTRADERS-1317 | Adding documents section to add items CYA

- app/controllers/addItems/ItemsCheckYourAnswersController.scala
- app/navigation/AddItemsNavigator.scala
- app/utils/AddItemsCheckYourAnswersHelper.scala
- app/viewModels/AddItemsCheckYourAnswersViewModel.scala
- conf/messages.en
- conf/views/addItems/itemsCheckYourAnswers.njk
- test/controllers/addItems/ItemsCheckYourAnswersControllerSpec.scala
- test/generators/PageGenerators.scala
- test/viewModels/AddItemsCheckYourAnswersViewModelSpec.scala
basic nav, basic CYA, removed packages and docs from CYA as not required at this stage
> Completion of basic journey

- app/forms/AuthorisedLocationCodeFormProvider.scala
- app/forms/CustomsApprovedLocationFormProvider.scala
- test/forms/AuthorisedLocationCodeFormProviderSpec.scala
- test/forms/CustomsApprovedLocationFormProviderSpec.scala
Updating to meet requirements in https://docs.google.com/spreadsheets/d/1lNs-jc7E2Xg3bdLo1ERutLd-ZEUzkHe4VwAwTcuBT1I/edit#gid=1603951763 (Goods Summary tab)
Note - This is required to allow E2E submission of 'Authorised Location of Goods' '954131533-GB60DEP'
> CTCTRADERS-791 | Adding acceptable special characters

- app/models/messages/DeclarationRequest.scala
- test/generators/JourneyModelGenerators.scala
- test/generators/MessagesModelGenerators.scala
- test/models/messages/DeclarationRequestSpec.scala
Noticed TraderAuthorisedConsignee was optional in xsd. Changed to reflect this.
> Make TraderAuthorisedConsignee optional

- app/models/journeyDomain/Packages.scala
- app/navigation/AddItemsNavigator.scala
- test/base/UserAnswersSpecHelper.scala
- test/generators/JourneyModelGenerators.scala
- test/generators/ModelGenerators.scala
- test/models/journeyDomain/PackagesSpec.scala
- CTCTRADERS-1098: Model structure
- Add Bulk and Other
- Add parser for UnpackedPackages
- Add parser for all Package types
- Don't call cleanup in useranswer helper on set or remove of a page
- Read packages based on routing questions.
> CTCTRADERS 1098 packages

- app/models/domain/Address.scala
- app/models/journeyDomain/ItemTraderDetails.scala
Fix app exception caused by tuple mismatch https://kibana.tools.staging.tax.service.gov.uk/goto/6048c382de368f54df41cfd8d62b425c
> Updating to pass consigneeAddress to prism

- app/navigation/TraderDetailsNavigator.scala
- app/utils/SectionsHelper.scala
- test/navigation/TraderDetailsNavigatorSpec.scala
- test/utils/SectionsHelperSpec.scala
- Updated section helper to divert based on questions answered (resolving issue where user can answer questions in order they should not be able to)
- Updated trader details nav in checkMode
> CTCTRADERS-1470 | Display correct status for Trader Details journey

- app/navigation/SecurityDetailsNavigator.scala
- test/navigation/SecurityDetailsNavigatorSpec.scala
> CTCTRADERS-1472: Updated nav following safety and security journey being implemented

- app/connectors/ReferenceDataConnector.scala
- app/controllers/routeDetails/AddAnotherTransitOfficeController.scala
- app/controllers/routeDetails/OfficeOfDepartureController.scala
- app/forms/AddAnotherTransitOfficeFormProvider.scala
- conf/views/addAnotherTransitOffice.njk
- test/controllers/routeDetails/AddAnotherTransitOfficeControllerSpec.scala
- test/forms/AddAnotherTransitOfficeFormProviderSpec.scala
Note - This lays the groundwork for the development ticket to follow CTCTRADERS-1833
> CTCTRADERS-1814 | Using destination country to filter customsOffices

- app/controllers/routeDetails/MovementDestinationCountryController.scala
- app/forms/MovementDestinationCountryFormProvider.scala
- app/pages/MovementDestinationCountryPage.scala
- app/utils/RouteDetailsCheckYourAnswersHelper.scala
- conf/app.routeDetails.routes
- conf/messages.en
- conf/views/movementDestinationCountry.njk
- test/controllers/routeDetails/MovementDestinationCountryControllerSpec.scala
- test/forms/MovementDestinationCountryFormProviderSpec.scala
- test/generators/UserAnswersEntryGenerators.scala
- test/generators/UserAnswersGenerator.scala
- test/pages/MovementDestinationCountryPageSpec.scala
Amended existing content for Destination Country and Destination Office. Created page for Movement Destination Country. There will be another PR for wiring the new page into nav and implementing the logic for retrieving and filtering countries.
> Ctctraders 1630 - Country/office of destination journey iteration

- app/controllers/routeDetails/DestinationCountryController.scala
- app/controllers/routeDetails/DestinationOfficeController.scala
- app/controllers/routeDetails/MovementDestinationCountryController.scala
- app/controllers/routeDetails/RouteDetailsCheckYourAnswersController.scala
- app/forms/MovementDestinationCountryFormProvider.scala
- app/navigation/RouteDetailsNavigator.scala
- app/pages/CountryOfDispatchPage.scala
- app/pages/DestinationCountryPage.scala
- app/pages/MovementDestinationCountryPage.scala
- app/utils/RouteDetailsCheckYourAnswersHelper.scala
- conf/views/destinationOffice.njk
- test/controllers/routeDetails/DestinationCountryControllerSpec.scala
- test/controllers/routeDetails/DestinationOfficeControllerSpec.scala
- test/controllers/routeDetails/MovementDestinationCountryControllerSpec.scala
- test/controllers/routeDetails/OfficeOfDepartureControllerSpec.scala
- test/controllers/routeDetails/RouteDetailsCheckYourAnswersControllerSpec.scala
- test/forms/MovementDestinationCountryFormProviderSpec.scala
- test/navigation/RouteDetailsNavigatorSpec.scala
- test/pages/MovementDestinationCountryPageSpec.scala
Amended logic for around handling countries/offices for Destination Country, Destination Office and Movement Destination Country. Implemented navigation to reflect newly amended journey.
> Ctctraders 1630 - Country/office of destination journey iteration 2/2

- app/models/messages/goodsitem/SpecialMention.scala
- test/models/messages/goodsitem/SpecialMentionSpec.scala
- in the special mentions AddInfMT21 should occur before AddInfCodMT23
> CTCTRADERS-2288 Reorder xml nodes for special mentions

- app/repositories/IndexLogMessages.scala
- app/repositories/SessionCollectionIndexManager.scala
- it/itSpecBase/ItSpecBase.scala
- it/repositories/FailOnUnindexedQueries.scala
- it/repositories/InterchangeControlReferenceIdRepositorySpec.scala
- it/repositories/MongoSuite.scala
- Add idex for eoriNumber
- Add info logging for result from index manager
- Add error logging when index manager throws exception
> CTCTRADERS-2237 Add index for eoriNumber in user-answers collection

- conf/views/accessCode.njk
- conf/views/addIdAtDeparture.njk
- conf/views/addItems/addAnotherItem.njk
- conf/views/addItems/addAnotherPackage.njk
- conf/views/addItems/addDocuments.njk
- conf/views/addItems/commodityCode.njk
- conf/views/addItems/traderDetails/traderDetailsConsigneeAddress.njk
- conf/views/addItems/traderDetails/traderDetailsConsignorAddress.njk
- conf/views/addItems/traderSecurityDetails/securityConsigneeAddress.njk
- conf/views/addItems/traderSecurityDetails/securityConsignorAddress.njk
- conf/views/confirmRemoveOfficeOfTransit.njk
- conf/views/consigneeAddress.njk
- conf/views/consignorAddress.njk
- conf/views/principalAddress.njk
- conf/views/procedureType.njk
- conf/views/safetyAndSecurity/addAnotherCountryOfRouting.njk
- conf/views/safetyAndSecurity/safetyAndSecurityConsigneeAddress.njk
- conf/views/safetyAndSecurity/safetyAndSecurityConsignorAddress.njk
- conf/views/sealsInformation.njk
Reverts hmrc/declare-transit-movement-departure-frontend#626
> Revert "CTCTRADERS-2385-Updated Radios and Address to use fieldsets and legends"
